# Generated by Django 5.2 on 2025-09-16 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CUEUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue', models.CharField(max_length=18, verbose_name='CUE')),
                ('anexo', models.CharField(blank=True, max_length=2, null=True, verbose_name='Anexo')),
                ('modalidad', models.CharField(blank=True, max_length=3, null=True, verbose_name='Modalidad')),
                ('nivel', models.CharField(blank=True, max_length=3, null=True, verbose_name='Nivel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
