# Generated by Django 5.2 on 2025-05-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cueusuario',
            name='anexo',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='cueusuario',
            name='modalidad',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='cueusuario',
            name='nivel',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='cueusuario',
            name='cue',
            field=models.CharField(max_length=7, verbose_name='CUE'),
        ),
    ]
