# Generated by Django 5.2 on 2025-05-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_cueusuario_anexo_cueusuario_modalidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cueusuario',
            name='cue',
            field=models.CharField(max_length=18, verbose_name='CUE'),
        ),
    ]
